# Generated by Django 3.2 on 2021-06-05 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('abundence', models.PositiveIntegerField()),
                ('profits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('radius', models.PositiveIntegerField()),
                ('trunk_wounds', models.PositiveIntegerField()),
                ('mushrooms', models.PositiveIntegerField()),
                ('surface_roots', models.CharField(max_length=20)),
                ('leaf_colour', models.CharField(max_length=20)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Species', to='backend.species')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
