# Generated by Django 3.2 on 2021-06-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210605_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='leaf_colour',
        ),
        migrations.AddField(
            model_name='tree',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='abundence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='profits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='surface_roots',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
