# Generated by Django 3.2 on 2021-06-05 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210605_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='tree_id',
        ),
    ]
