# Generated by Django 3.2 on 2021-06-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_tree_tree_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='max_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='moisture',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='shade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='soil',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
